version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next_phorarios
    ports:
      - 8001:8001
    volumes:
      - ./next-horarios:/app
      - ./cert:/app/cert
    environment:
      - HTTPS=true
      - SSL_CERT=/app/cert/NetlifeNetEc1.crt.pem
      - SSL_KEY=/app/cert/netlifeNetEc1.key.pem
